set-option -g prefix F12
unbind C-b

bind -N "Reload Config" r \
     source-file ~/.config/tmux/tmux.conf \; \
     display-message "tmux config reloaded!"


bind -N "Split window..." s switch-client -T split-mode
bind -N "Split window vertically"   -T split-mode v split-window -v -c "#{pane_current_path}"
bind -N "Split window horizontally" -T split-mode h split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %

# Overlay help window
unbind ?
bind -N "Show key bindings" ? display-popup -w 80% -h 80% "tmux list-keys -N | fzf"

# Styling and Theming
set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
set-option -g status-style bg=default
set -g @catppuccin_status_bg "default"

# Status bar
set-option -g status-position top
set -g 'status-format[1]' ''
set -g status 2

set -g status-left " "
set -g status-right ""

set-option -g focus-events on
run-shell "~/.config/tmux/plugins/update-pane-pills-env"
set-hook -g pane-exited 'run-shell "~/.config/tmux/plugins/update-pane-pills-env"'
set-hook -g pane-focus-in 'run-shell "~/.config/tmux/plugins/update-pane-pills-env"'
set-hook -g pane-focus-out 'run-shell "~/.config/tmux/plugins/update-pane-pills-env"'

set -g window-status-format "#[fg=#{@thm_sky},bg=default] "
set -g window-status-current-format "#[fg=#{@thm_sky},bg=default] "

# Miscelenious
set-option -g base-index 1

