set-option -g prefix F12
unbind C-b

bind -N "Reload Config" r \
     source-file ~/.config/tmux/tmux.conf \; \
     display-message "tmux config reloaded!"


bind -N "Split window..." s switch-client -T split-mode
bind -N "Split window vertically"   -T split-mode v split-window -v -c "#{pane_current_path}"
bind -N "Split window horizontally" -T split-mode h split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %

# Pane Management
unbind p
unbind n

bind -N "Select previous pane" [ run-shell "~/.config/tmux/plugins/select-relative-pane prev"
bind -N "Select next pane" ] run-shell "~/.config/tmux/plugins/select-relative-pane next"

bind -N "Select Pane..." p switch-client -T pane-mode

bind -T pane-mode 1 select-pane -Z -t 1 \; switch-client -T root
bind -T pane-mode 2 select-pane -Z -t 2 \; switch-client -T root
bind -T pane-mode 3 select-pane -Z -t 3 \; switch-client -T root
bind -T pane-mode 4 select-pane -Z -t r \; switch-client -T root
bind -T pane-mode 5 select-pane -Z -t 5 \; switch-client -T root
bind -T pane-mode 6 select-pane -Z -t 6 \; switch-client -T root
bind -T pane-mode 7 select-pane -Z -t 7 \; switch-client -T root
bind -T pane-mode 8 select-pane -Z -t 8 \; switch-client -T root
bind -T pane-mode 9 select-pane -Z -t 9 \; switch-client -T root
bind -T pane-mode 0 select-pane -Z -t 0 \; switch-client -T root
bind -T pane-mode q display-panes
bind -T pane-mode [ run-shell "~/.config/tmux/plugins/select-relative-pane prev" \; switch-client -T root
bind -T pane-mode ] run-shell "~/.config/tmux/plugins/select-relative-pane next" \; switch-client -T root


# Overlay help window
unbind ?
bind -N "Show key bindings" ? display-popup -w 80% -h 80% "tmux list-keys -N | fzf"

# Styling and Theming
set -g @catppuccin_flavor 'mocha'
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
set-option -g status-style bg=default
set -g @catppuccin_status_bg "default"

# Status bar
set-option -g status-position top
set -g 'status-format[1]' ''
set -g status 2

set -g status-left " "
set -g status-right ""

set-option -g focus-events on
run-shell "~/.config/tmux/plugins/update-pane-pills-env"
set-hook -g pane-exited 'run-shell "~/.config/tmux/plugins/update-pane-pills-env"'
set-hook -g pane-focus-in 'run-shell "~/.config/tmux/plugins/update-pane-pills-env"'
set-hook -g pane-focus-out 'run-shell "~/.config/tmux/plugins/update-pane-pills-env"'

set -g window-status-format "#[fg=#{@thm_sky},bg=default] "
set -g window-status-current-format "#[fg=#{@thm_sky},bg=default] "

# Miscelenious
set-option -g base-index 1
set -g mode-keys vi
set -g mouse on

