# Load FSH & Catppuccin for FSH
source ~/.config/zsh/plugins/fsh/fast-syntax-highlighting.plugin.zsh
fast-theme catppuccin-mocha 1>/dev/null

autoload -U promptinit; promptinit
# Load Pure (theme)
# fpath+=($HOME/.config/zsh/plugins/pure)
# prompt pure
# zstyle :prompt:pure:prompt:success color green

# Custom prompt
_COL=${OSCOLOR:-cyan}
_ICON=${OSICON:-$'\uf179'}
_FOLDER=$'\uf07b'
PS1="%F{$_COL}$_ICON%f "
RPROMPT="%F{$_COL}$_FOLDER %1~%f"
echo '\e[5 q'

