# Load FSH & Catppuccin for FSH
source ~/.config/zsh/plugins/fsh/fast-syntax-highlighting.plugin.zsh
fast-theme catppuccin-mocha

# Load Pure (theme)
fpath+=($HOME/.config/zsh/plugins/pure)
autoload -U promptinit; promptinit
prompt pure

